export WATSON_API_KEY=xxx
export WATSON_URL=xxx
export WATSON_PROJECT_ID=xxx
export BAM_API_KEY=xxx
export OPENAI_API_KEY=xxx
export WD_COLLECTION_IDS="[\"xxx-xxx-xxx-xx-xxx\",\"xxx-xxx-xxx-xx-xxx\"]"
export DATASTORE=xx
export BEARER_TOKEN=<your database interface api>
export OPENAI_API_KEY=xxx
export PINECONE_API_KEY=xxx
export PINECONE_ENVIRONMENT=xxx
export PINECONE_INDEX=xxx
export DATABASE_BEARER_TOKEN=<your database interface api>
